### ISSUE TITLE
relly nice node group.wow~

### ISSUE THREAD

**Issue by suicaoya123** [cgvirus/blender-geometry-nodes-collection#1]
about ground color blend node. how to imput an collection group as origin source？

**Comment by cgvirus** [comment]
Hi thanks, yes it can be done.

1. Go inside the color blend node using tab. 
2. replace object info node with collection info node 
3. use relative
4. connect it in Target socket of attribute proximity node
![Screenshot from 2021-10-20 19-05-46](https://user-images.githubusercontent.com/22106885/138098817-60d328b7-7080-4c66-aa4b-9fd4d2259cc1.jpg)
